name: Practice
on: push
jobs: 
    Installing_scripts:
        runs-on: ubuntu-latest
        steps:
            - name: Get code on the machine
              uses: actions/checkout@v7
            - name: install nodejs
              uses: actions/setup-node@v6
            - name: lint
              run: npm run lint
            - name: build
              run: npm run build
            - name: test
              run: npm run test

